Q_ANGLE_T = 8
Q_ANGLE_P = 8

FILTER_LEN = 11
FILTER_HALF = FILTER_LEN // 2

# Do not edit!
Q_STRENGTH = 3
Q_COHERENCE = 3
PIXEL_TYPE = 2 ** 3

Q_TOTAL = Q_ANGLE_P * Q_ANGLE_T * Q_STRENGTH * Q_COHERENCE
FILTER_VOL = FILTER_LEN ** 3

TPB = 32